version: "2.3"
services:
  app:
    image: node:14.15.1-alpine
    expose:
      - 3000
    volumes:
      - $PWD:/home/node
    user: node
    working_dir: /home/node
    restart: "always"
    command: "sh -c 'npm run start:prod'"
    network_mode: bridge
